### ISSUE TITLE
question: Continue with CGO?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [ada-url/goada#2]
Hi,

You are currently using the C++ library via CGO.

Will it always be this way or are you considering writing a raw golang implementation?

**Comment by lemire** [comment]
The C++ library spans 20,000 lines of code. It is non trivial code. If you are interested in porting it to Go, we are certainly inviting pull requests. Otherwise there is no plan to port it.

**Comment by SeanTolstoyevski** [comment]
Hello Daniel,

Thanks for your answer.

Since I don't know assembly, I can't port the same code, but I will take time for this.

**Comment by lemire** [comment]
We do not use assembly, it is just C++.
