### ISSUE TITLE
make a compareString function for goada_test.go

### ISSUE THREAD

**Issue by mertcanaltin** [ada-url/goada#4]
@lemire @anonrig  hi  add helper functions to prevent this code repetition? For example, if I create a helper function called compareString like 

this: 

```go
func compareString(t *testing.T, expected, actual, message string) {
	if expected != actual {
		t.Errorf("Expected %s, but got %s. %s", expected, actual, message)
	}
}
```

**Comment by lemire** [comment]
That would be fine. PR invited.

**Comment by mertcanaltin** [comment]
> That would be fine. PR invited.

ı created it here : [pr](https://github.com/ada-url/goada/pull/5)
